- hosts: localhost
  tasks:
    - name: Create shipa framework
      shipa_framework:
        shipa_host: <host>
        shipa_token: <token>
        name: hello-ansible-4
        resources:
          general:
            setup:
              provisioner: kubernetes
            access:
              append: ["shipa-team"]
            plan:
              name: shipa-plan
            router: traefik
            security:
              disableScan: false
              ignoreCves: [ "CVE-2019-16782", "CVE-2018-16471", "CVE-2018-16470", "CVE-2020-8161" ]
              ignoreComponents: [ "glibc", "django" ]
            appQuota:
              limit: "5"
            networkPolicy:
              ingress:
                policy_mode: allow-all
              egress:
                policy_mode: allow-all
              disableAppPolicies: false
            containerPolicy:
              allowedHosts: [ "docker.io/shipasoftware" ]

#      register: result
#    - debug: var=result