- hosts: localhost
  vars:
    - shipa_host: <host>
    - shipa_token: <token>
  tasks:
    - name: Create shipa framework
      shipa_framework:
        shipa_host: "{{ shipa_host }}"
        shipa_token: "{{ shipa_token }}"
        name: ansible-fm-3
        resources:
          general:
            setup:
              provisioner: kubernetes
            access:
              append: ["shipa-team"]
            plan:
              name: shipa-plan
            router: nginx
            security:
              disableScan: false
              ignoreCves: [ "CVE-2019-16782", "CVE-2018-16471", "CVE-2018-16470", "CVE-2020-8161" ]
              ignoreComponents: [ "glibc", "django" ]
            appQuota:
              limit: "5"
            networkPolicy:
              ingress:
                policy_mode: allow-all
              egress:
                policy_mode: allow-all
              disableAppPolicies: false
            containerPolicy:
              allowedHosts: [ "docker.io/shipasoftware" ]

    - name: Create shipa cluster
      shipa_cluster:
        shipa_host: "{{ shipa_host }}"
        shipa_token: "{{ shipa_token }}"
        name: ansible-cl-2
        endpoint:
          addresses:
            - https://34.72.90.235
          caCert: ./cert/caCert
          token: ./cert/token
        resources:
          frameworks:
            - name: ansible-fm-3

    - name: Create shipa application
      shipa_application:
        shipa_host: "{{ shipa_host }}"
        shipa_token: "{{ shipa_token }}"
        name: ansible-app-2
        teamowner: shipa-team
        framework: dev

    - name: Deploy shipa application
      shipa_app_deploy:
        shipa_host: "{{ shipa_host }}"
        shipa_token: "{{ shipa_token }}"
        app: ansible-app-2
        image: docker.io/shipasoftware/bulletinboard:1.0
        port: 8000

    - name: Create shipa app cname
      shipa_app_cname:
        shipa_host: "{{ shipa_host }}"
        shipa_token: "{{ shipa_token }}"
        app: ansible-app-2
        cname: shipa.team
        scheme: http
