- hosts: localhost
  vars:
    - shipa_host: <host>
    - shipa_token: <token>
  tasks:
    - name: Create shipa framework
      shipa_framework:
        shipa_host: "{{ shipa_host }}"
        shipa_token: "{{ shipa_token }}"
        name: ansible-fm-1
        resources:
          general:
            setup:
              provisioner: kubernetes
            access:
              append: ["shipa-team"]
            plan:
              name: shipa-plan
            router: nginx
            security:
              disableScan: false
#              ignoreCves: [ "CVE-2019-16782", "CVE-2018-16471", "CVE-2018-16470", "CVE-2020-8161" ]
#              ignoreComponents: [ "glibc", "django" ]
            appQuota:
              limit: "5"
            networkPolicy:
              ingress:
                policy_mode: allow-all
              egress:
                policy_mode: allow-all
              disableAppPolicies: false
            containerPolicy:
              allowedHosts: [ "docker.io/shipasoftware" ]

    - name: Create shipa cluster
      shipa_cluster:
        shipa_host: "{{ shipa_host }}"
        shipa_token: "{{ shipa_token }}"
        name: ansible-cl-1
        endpoint:
          addresses:
            - https://34.67.82.140
          caCert: ./cert/caCert
          token: ./cert/token
        resources:
          frameworks:
            - name: ansible-fm-1

    - name: Create shipa application
      shipa_application:
        shipa_host: "{{ shipa_host }}"
        shipa_token: "{{ shipa_token }}"
        name: ansible-app-1
        teamowner: shipa-team
        framework: shipayaml
        plan: dev
        tags: ["dev"]

    - name: Deploy shipa application
      shipa_app_deploy:
        shipa_host: "{{ shipa_host }}"
        shipa_token: "{{ shipa_token }}"
        app: ansible-app-1
        image: docker.io/shipasoftware/go-app:v1
        port: 8000

    - name: Create shipa app cname
      shipa_app_cname:
        shipa_host: "{{ shipa_host }}"
        shipa_token: "{{ shipa_token }}"
        app: ansible-app-2
        cname: shipa.team
        encrypt: false

    - name: Create shipa app env
      shipa_app_env:
        shipa_host: "{{ shipa_host }}"
        shipa_token: "{{ shipa_token }}"
        app: ansible-app-2
        envs:
          - name: ANSIBLE_ENV_1
            value: ansible-value-1
          - name: ANSIBLE_ENV_2
            value: ansible-value-2

    - name: Create shipa network policy
      shipa_network_policy:
        shipa_host: "{{ shipa_host }}"
        shipa_token: "{{ shipa_token }}"
        app: ansible-app-2
        ingress:
          policy_mode: allow-custom-rules-only
          custom_rules:
            - id: gateway
              enabled: true
              description: gateway block test
              allowed_pools:
                - dev-ansible-policy
        egress:
          policy_mode: allow-all
        restart_app: false

    - name: Create shipa job
      shipa_job:
        shipa_host: "{{ shipa_host }}"
        shipa_token: "{{ shipa_token }}"
        name: ansible-job-1
        framework: shipayaml
        policy:
          restartPolicy: Never
        containers:
          - name: job
            image: golang:1.16
            command: [ "/bin/bash", "ls", "-l" ]
